//////////////////////// profile.h make from profile.hh

//////////////////////// definition of EXTERNs counters

unsigned int _OPTIMIZED_MOVE ;
unsigned int _ADDA_L_To_Ax ;
unsigned int _ADDA_W_To_Ax ;
unsigned int _ADDI_B_To_Dx ;
unsigned int _ADDI_B_To_Mem ;
unsigned int _ADDI_L_To_Dx ;
unsigned int _ADDI_L_To_Mem ;
unsigned int _ADDI_W_To_Dx ;
unsigned int _ADDI_W_To_Mem ;
unsigned int _ADDQ_B_Dx ;
unsigned int _ADDQ_B_mem ;
unsigned int _ADDQ_L_Ax ;
unsigned int _ADDQ_L_Dx ;
unsigned int _ADDQ_L_mem ;
unsigned int _ADDQ_W_Ax ;
unsigned int _ADDQ_W_Dx ;
unsigned int _ADDQ_W_mem ;
unsigned int _ADDX_B_Aipd ;
unsigned int _ADDX_B_Dx ;
unsigned int _ADDX_L_Aipd ;
unsigned int _ADDX_L_Dx ;
unsigned int _ADDX_W_Aipd ;
unsigned int _ADDX_W_Dx ;
unsigned int _ADD_B_Dx_To_EA ;
unsigned int _ADD_B_EA_To_Dx ;
unsigned int _ADD_L_Dx_To_EA ;
unsigned int _ADD_L_EA_To_Dx ;
unsigned int _ADD_W_Dx_To_EA ;
unsigned int _ADD_W_EA_To_Dx ;
unsigned int _ANDI_B_To_Dx ;
unsigned int _ANDI_B_To_Mem ;
unsigned int _ANDI_CCR ;
unsigned int _ANDI_L_To_Dx ;
unsigned int _ANDI_L_To_Mem ;
unsigned int _ANDI_SR ;
unsigned int _ANDI_W_To_Dx ;
unsigned int _ANDI_W_To_Mem ;
unsigned int _AND_B_Dx_To_Dx ;
unsigned int _AND_B_Dx_To_Mem ;
unsigned int _AND_B_Mem_To_Dx ;
unsigned int _AND_L_Dx_To_Dx ;
unsigned int _AND_L_Dx_To_Mem ;
unsigned int _AND_L_Mem_To_Dx ;
unsigned int _AND_W_Dx_To_Dx ;
unsigned int _AND_W_Dx_To_Mem ;
unsigned int _AND_W_Mem_To_Dx ;
unsigned int _ASL_B_Dx_Dx ;
unsigned int _ASL_B_Nb_Dx ;
unsigned int _ASL_L_Dx_Dx ;
unsigned int _ASL_L_Nb_Dx ;
unsigned int _ASL_W_Dx_Dx ;
unsigned int _ASL_W_Nb_Dx ;
unsigned int _ASL_W_mem ;
unsigned int _ASR_B_Dx_Dx ;
unsigned int _ASR_B_Nb_Dx ;
unsigned int _ASR_L_Dx_Dx ;
unsigned int _ASR_L_Nb_Dx ;
unsigned int _ASR_W_Dx_Dx ;
unsigned int _ASR_W_Nb_Dx ;
unsigned int _ASR_W_mem ;
unsigned int _BCC_Long ;
unsigned int _BCC_Short ;
unsigned int _BCHG_B_Dx_mem ;
unsigned int _BCHG_B_Nb_mem ;
unsigned int _BCHG_L_Dx_Dx ;
unsigned int _BCHG_L_Nb_Dx ;
unsigned int _BCLR_B_Dx_mem ;
unsigned int _BCLR_B_Nb_mem ;
unsigned int _BCLR_L_Dx_Dx ;
unsigned int _BCLR_L_Nb_Dx ;
unsigned int _BCS_Long ;
unsigned int _BCS_Short ;
unsigned int _BEQ_Long ;
unsigned int _BEQ_Short ;
unsigned int _BGE_Long ;
unsigned int _BGE_Short ;
unsigned int _BGT_Long ;
unsigned int _BGT_Short ;
unsigned int _BHI_Long ;
unsigned int _BHI_Short ;
unsigned int _BLE_Long ;
unsigned int _BLE_Short ;
unsigned int _BLS_Long ;
unsigned int _BLS_Short ;
unsigned int _BLT_Long ;
unsigned int _BLT_Short ;
unsigned int _BMI_Long ;
unsigned int _BMI_Short ;
unsigned int _BNE_Long ;
unsigned int _BNE_Short ;
unsigned int _BPL_Long ;
unsigned int _BPL_Short ;
unsigned int _BRA_Long ;
unsigned int _BRA_Short ;
unsigned int _BSET_B_Dx_mem ;
unsigned int _BSET_B_Nb_mem ;
unsigned int _BSET_L_Dx_Dx ;
unsigned int _BSET_L_Nb_Dx ;
unsigned int _BSR_Long ;
unsigned int _BSR_Short ;
unsigned int _BTST_B_Dx_mem ;
unsigned int _BTST_B_Nb_mem ;
unsigned int _BTST_L_Dx_Dx ;
unsigned int _BTST_L_Nb_Dx ;
unsigned int _BVC_Long ;
unsigned int _BVC_Short ;
unsigned int _BVS_Long ;
unsigned int _BVS_Short ;
unsigned int _CHK_Dx ;
unsigned int _CHK_mem ;
unsigned int _CLR_B ;
unsigned int _CLR_L ;
unsigned int _CLR_W ;
unsigned int _CMPA_L ;
unsigned int _CMPA_W ;
unsigned int _CMPI_B_Dx ;
unsigned int _CMPI_B_Mem ;
unsigned int _CMPI_L_Dx ;
unsigned int _CMPI_L_Mem ;
unsigned int _CMPI_W_Dx ;
unsigned int _CMPI_W_Mem ;
unsigned int _CMPM_B ;
unsigned int _CMPM_L ;
unsigned int _CMPM_W ;
unsigned int _CMP_B_Dx ;
unsigned int _CMP_L_Dx ;
unsigned int _CMP_W_Dx ;
unsigned int _DBCC ;
unsigned int _DBCS ;
unsigned int _DBEQ ;
unsigned int _DBF ;
unsigned int _DBGE ;
unsigned int _DBGT ;
unsigned int _DBHI ;
unsigned int _DBLE ;
unsigned int _DBLS ;
unsigned int _DBLT ;
unsigned int _DBMI ;
unsigned int _DBNE ;
unsigned int _DBPL ;
unsigned int _DBT ;
unsigned int _DBVC ;
unsigned int _DBVS ;
unsigned int _DIVS ;
unsigned int _DIVU ;
unsigned int _EORI_B_To_Dx ;
unsigned int _EORI_B_To_Mem ;
unsigned int _EORI_CCR ;
unsigned int _EORI_L_To_Dx ;
unsigned int _EORI_L_To_Mem ;
unsigned int _EORI_SR ;
unsigned int _EORI_W_To_Dx ;
unsigned int _EORI_W_To_Mem ;
unsigned int _EOR_B_Dx_To_Dx ;
unsigned int _EOR_B_Dx_To_Mem ;
unsigned int _EOR_B_Mem_To_Dx ;
unsigned int _EOR_L_Dx_To_Dx ;
unsigned int _EOR_L_Dx_To_Mem ;
unsigned int _EOR_L_Mem_To_Dx ;
unsigned int _EOR_W_Dx_To_Dx ;
unsigned int _EOR_W_Dx_To_Mem ;
unsigned int _EOR_W_Mem_To_Dx ;
unsigned int _EXG_Ax_Ax ;
unsigned int _EXG_Dx_Ax ;
unsigned int _EXG_Dx_Dx ;
unsigned int _EXT_L ;
unsigned int _EXT_W ;
unsigned int _JMP ;
unsigned int _JSR ;
unsigned int _LEA ;
unsigned int _LINK ;
unsigned int _LSL_B_Dx_Dx ;
unsigned int _LSL_B_Nb_Dx ;
unsigned int _LSL_L_Dx_Dx ;
unsigned int _LSL_L_Nb_Dx ;
unsigned int _LSL_W_Dx_Dx ;
unsigned int _LSL_W_Nb_Dx ;
unsigned int _LSL_W_mem ;
unsigned int _LSR_B_Dx_Dx ;
unsigned int _LSR_B_Nb_Dx ;
unsigned int _LSR_L_Dx_Dx ;
unsigned int _LSR_L_Nb_Dx ;
unsigned int _LSR_W_Dx_Dx ;
unsigned int _LSR_W_Nb_Dx ;
unsigned int _LSR_W_mem ;
unsigned int _MOVEA_L_Ax ;
unsigned int _MOVEA_L_Dx ;
unsigned int _MOVEA_L_mem ;
unsigned int _MOVEA_W_Ax ;
unsigned int _MOVEA_W_Dx ;
unsigned int _MOVEA_W_mem ;
unsigned int _MOVEM_L_from_mem ;
unsigned int _MOVEM_L_from_mem_Aipi ;
unsigned int _MOVEM_L_to_mem ;
unsigned int _MOVEM_L_to_mem_Aipd ;
unsigned int _MOVEM_W_from_mem ;
unsigned int _MOVEM_W_from_mem_Aipi ;
unsigned int _MOVEM_W_to_mem ;
unsigned int _MOVEM_W_to_mem_Aipd ;
unsigned int _MOVEP_L_From_Mem ;
unsigned int _MOVEP_L_To_Mem ;
unsigned int _MOVEP_W_From_Mem ;
unsigned int _MOVEP_W_To_Mem ;
unsigned int _MOVEQ ;
unsigned int _MOVE_B ;
unsigned int _MOVE_From_SR ;
unsigned int _MOVE_From_USP ;
unsigned int _MOVE_L ;
unsigned int _MOVE_To_CCR ;
unsigned int _MOVE_To_SR ;
unsigned int _MOVE_To_USP ;
unsigned int _MOVE_W ;
unsigned int _MULS ;
unsigned int _MULU ;
unsigned int _NEGX_B_Dx ;
unsigned int _NEGX_B_Mem ;
unsigned int _NEGX_L_Dx ;
unsigned int _NEGX_L_Mem ;
unsigned int _NEGX_W_Dx ;
unsigned int _NEGX_W_Mem ;
unsigned int _NEG_B_Dx ;
unsigned int _NEG_B_Mem ;
unsigned int _NEG_L_Dx ;
unsigned int _NEG_L_Mem ;
unsigned int _NEG_W_Dx ;
unsigned int _NEG_W_Mem ;
unsigned int _NOP ;
unsigned int _NOT_B_Dx ;
unsigned int _NOT_B_Mem ;
unsigned int _NOT_L_Dx ;
unsigned int _NOT_L_Mem ;
unsigned int _NOT_W_Dx ;
unsigned int _NOT_W_Mem ;
unsigned int _ORI_B_To_Dx ;
unsigned int _ORI_B_To_Mem ;
unsigned int _ORI_CCR ;
unsigned int _ORI_L_To_Dx ;
unsigned int _ORI_L_To_Mem ;
unsigned int _ORI_SR ;
unsigned int _ORI_W_To_Dx ;
unsigned int _ORI_W_To_Mem ;
unsigned int _OR_B_Dx_To_Dx ;
unsigned int _OR_B_Dx_To_Mem ;
unsigned int _OR_B_Mem_To_Dx ;
unsigned int _OR_L_Dx_To_Dx ;
unsigned int _OR_L_Dx_To_Mem ;
unsigned int _OR_L_Mem_To_Dx ;
unsigned int _OR_W_Dx_To_Dx ;
unsigned int _OR_W_Dx_To_Mem ;
unsigned int _OR_W_Mem_To_Dx ;
unsigned int _PEA ;
unsigned int _RESET ;
unsigned int _ROL_B_Dx_Dx ;
unsigned int _ROL_B_Nb_Dx ;
unsigned int _ROL_L_Dx_Dx ;
unsigned int _ROL_L_Nb_Dx ;
unsigned int _ROL_W_Dx_Dx ;
unsigned int _ROL_W_Nb_Dx ;
unsigned int _ROL_W_mem ;
unsigned int _ROR_B_Dx_Dx ;
unsigned int _ROR_B_Nb_Dx ;
unsigned int _ROR_L_Dx_Dx ;
unsigned int _ROR_L_Nb_Dx ;
unsigned int _ROR_W_Dx_Dx ;
unsigned int _ROR_W_Nb_Dx ;
unsigned int _ROR_W_mem ;
unsigned int _ROXL_B_Dx_Dx ;
unsigned int _ROXL_B_Nb_Dx ;
unsigned int _ROXL_L_Dx_Dx ;
unsigned int _ROXL_L_Nb_Dx ;
unsigned int _ROXL_W_Dx_Dx ;
unsigned int _ROXL_W_Nb_Dx ;
unsigned int _ROXL_W_mem ;
unsigned int _ROXR_B_Dx_Dx ;
unsigned int _ROXR_B_Nb_Dx ;
unsigned int _ROXR_L_Dx_Dx ;
unsigned int _ROXR_L_Nb_Dx ;
unsigned int _ROXR_W_Dx_Dx ;
unsigned int _ROXR_W_Nb_Dx ;
unsigned int _ROXR_W_mem ;
unsigned int _RTE ;
unsigned int _RTR ;
unsigned int _RTS ;
unsigned int _SCC ;
unsigned int _SCS ;
unsigned int _SEQ ;
unsigned int _SF ;
unsigned int _SGE ;
unsigned int _SGT ;
unsigned int _SHI ;
unsigned int _SLE ;
unsigned int _SLS ;
unsigned int _SLT ;
unsigned int _SMI ;
unsigned int _SNE ;
unsigned int _SPL ;
unsigned int _ST ;
unsigned int _SUBA_L_To_Ax ;
unsigned int _SUBA_W_To_Ax ;
unsigned int _SUBI_B_To_Dx ;
unsigned int _SUBI_B_To_Mem ;
unsigned int _SUBI_L_To_Dx ;
unsigned int _SUBI_L_To_Mem ;
unsigned int _SUBI_W_To_Dx ;
unsigned int _SUBI_W_To_Mem ;
unsigned int _SUBQ_B_Dx ;
unsigned int _SUBQ_B_mem ;
unsigned int _SUBQ_L_Ax ;
unsigned int _SUBQ_L_Dx ;
unsigned int _SUBQ_L_mem ;
unsigned int _SUBQ_W_Ax ;
unsigned int _SUBQ_W_Dx ;
unsigned int _SUBQ_W_mem ;
unsigned int _SUBX_B_Aipd ;
unsigned int _SUBX_B_Dx ;
unsigned int _SUBX_L_Aipd ;
unsigned int _SUBX_L_Dx ;
unsigned int _SUBX_W_Aipd ;
unsigned int _SUBX_W_Dx ;
unsigned int _SUB_B_Dx_To_EA ;
unsigned int _SUB_B_EA_To_Dx ;
unsigned int _SUB_L_Dx_To_EA ;
unsigned int _SUB_L_EA_To_Dx ;
unsigned int _SUB_W_Dx_To_EA ;
unsigned int _SUB_W_EA_To_Dx ;
unsigned int _SVC ;
unsigned int _SVS ;
unsigned int _Swap ;
unsigned int _TRAP ;
unsigned int _TRAPV ;
unsigned int _TST_B_Dx ;
unsigned int _TST_B_Mem ;
unsigned int _TST_L_Dx ;
unsigned int _TST_L_Mem ;
unsigned int _TST_W_Dx ;
unsigned int _TST_W_Mem ;
unsigned int _UNLK ;


void profile_all_functions(void)
{
char b[100] ;
        sprintf(b,"%10d -> Do_ADDA_L_To_Ax",_ADDA_L_To_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDA_W_To_Ax",_ADDA_W_To_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDI_B_To_Dx",_ADDI_B_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDI_B_To_Mem",_ADDI_B_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDI_L_To_Dx",_ADDI_L_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDI_L_To_Mem",_ADDI_L_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDI_W_To_Dx",_ADDI_W_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDI_W_To_Mem",_ADDI_W_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_B_Dx",_ADDQ_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_B_mem",_ADDQ_B_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_L_Ax",_ADDQ_L_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_L_Dx",_ADDQ_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_L_mem",_ADDQ_L_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_W_Ax",_ADDQ_W_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_W_Dx",_ADDQ_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDQ_W_mem",_ADDQ_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDX_B_Aipd",_ADDX_B_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDX_B_Dx",_ADDX_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDX_L_Aipd",_ADDX_L_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDX_L_Dx",_ADDX_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDX_W_Aipd",_ADDX_W_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADDX_W_Dx",_ADDX_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADD_B_Dx_To_EA",_ADD_B_Dx_To_EA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADD_B_EA_To_Dx",_ADD_B_EA_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADD_L_Dx_To_EA",_ADD_L_Dx_To_EA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADD_L_EA_To_Dx",_ADD_L_EA_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADD_W_Dx_To_EA",_ADD_W_Dx_To_EA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ADD_W_EA_To_Dx",_ADD_W_EA_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_B_To_Dx",_ANDI_B_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_B_To_Mem",_ANDI_B_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_CCR",_ANDI_CCR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_L_To_Dx",_ANDI_L_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_L_To_Mem",_ANDI_L_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_SR",_ANDI_SR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_W_To_Dx",_ANDI_W_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ANDI_W_To_Mem",_ANDI_W_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_B_Dx_To_Dx",_AND_B_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_B_Dx_To_Mem",_AND_B_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_B_Mem_To_Dx",_AND_B_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_L_Dx_To_Dx",_AND_L_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_L_Dx_To_Mem",_AND_L_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_L_Mem_To_Dx",_AND_L_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_W_Dx_To_Dx",_AND_W_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_W_Dx_To_Mem",_AND_W_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_AND_W_Mem_To_Dx",_AND_W_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_B_Dx_Dx",_ASL_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_B_Nb_Dx",_ASL_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_L_Dx_Dx",_ASL_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_L_Nb_Dx",_ASL_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_W_Dx_Dx",_ASL_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_W_Nb_Dx",_ASL_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASL_W_mem",_ASL_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_B_Dx_Dx",_ASR_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_B_Nb_Dx",_ASR_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_L_Dx_Dx",_ASR_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_L_Nb_Dx",_ASR_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_W_Dx_Dx",_ASR_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_W_Nb_Dx",_ASR_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ASR_W_mem",_ASR_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCC_Long",_BCC_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCC_Short",_BCC_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCHG_B_Dx_mem",_BCHG_B_Dx_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCHG_B_Nb_mem",_BCHG_B_Nb_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCHG_L_Dx_Dx",_BCHG_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCHG_L_Nb_Dx",_BCHG_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCLR_B_Dx_mem",_BCLR_B_Dx_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCLR_B_Nb_mem",_BCLR_B_Nb_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCLR_L_Dx_Dx",_BCLR_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCLR_L_Nb_Dx",_BCLR_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCS_Long",_BCS_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BCS_Short",_BCS_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BEQ_Long",_BEQ_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BEQ_Short",_BEQ_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BGE_Long",_BGE_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BGE_Short",_BGE_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BGT_Long",_BGT_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BGT_Short",_BGT_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BHI_Long",_BHI_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BHI_Short",_BHI_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BLE_Long",_BLE_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BLE_Short",_BLE_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BLS_Long",_BLS_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BLS_Short",_BLS_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BLT_Long",_BLT_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BLT_Short",_BLT_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BMI_Long",_BMI_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BMI_Short",_BMI_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BNE_Long",_BNE_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BNE_Short",_BNE_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BPL_Long",_BPL_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BPL_Short",_BPL_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BRA_Long",_BRA_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BRA_Short",_BRA_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BSET_B_Dx_mem",_BSET_B_Dx_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BSET_B_Nb_mem",_BSET_B_Nb_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BSET_L_Dx_Dx",_BSET_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BSET_L_Nb_Dx",_BSET_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BSR_Long",_BSR_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BSR_Short",_BSR_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BTST_B_Dx_mem",_BTST_B_Dx_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BTST_B_Nb_mem",_BTST_B_Nb_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BTST_L_Dx_Dx",_BTST_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BTST_L_Nb_Dx",_BTST_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BVC_Long",_BVC_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BVC_Short",_BVC_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BVS_Long",_BVS_Long) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_BVS_Short",_BVS_Short) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CHK_Dx",_CHK_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CHK_mem",_CHK_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CLR_B",_CLR_B) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CLR_L",_CLR_L) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CLR_W",_CLR_W) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPA_L",_CMPA_L) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPA_W",_CMPA_W) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPI_B_Dx",_CMPI_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPI_B_Mem",_CMPI_B_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPI_L_Dx",_CMPI_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPI_L_Mem",_CMPI_L_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPI_W_Dx",_CMPI_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPI_W_Mem",_CMPI_W_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPM_B",_CMPM_B) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPM_L",_CMPM_L) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMPM_W",_CMPM_W) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMP_B_Dx",_CMP_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMP_L_Dx",_CMP_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_CMP_W_Dx",_CMP_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBCC",_DBCC) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBCS",_DBCS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBEQ",_DBEQ) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBF",_DBF) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBGE",_DBGE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBGT",_DBGT) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBHI",_DBHI) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBLE",_DBLE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBLS",_DBLS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBLT",_DBLT) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBMI",_DBMI) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBNE",_DBNE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBPL",_DBPL) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBT",_DBT) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBVC",_DBVC) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DBVS",_DBVS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DIVS",_DIVS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_DIVU",_DIVU) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_B_To_Dx",_EORI_B_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_B_To_Mem",_EORI_B_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_CCR",_EORI_CCR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_L_To_Dx",_EORI_L_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_L_To_Mem",_EORI_L_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_SR",_EORI_SR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_W_To_Dx",_EORI_W_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EORI_W_To_Mem",_EORI_W_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_B_Dx_To_Dx",_EOR_B_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_B_Dx_To_Mem",_EOR_B_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_B_Mem_To_Dx",_EOR_B_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_L_Dx_To_Dx",_EOR_L_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_L_Dx_To_Mem",_EOR_L_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_L_Mem_To_Dx",_EOR_L_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_W_Dx_To_Dx",_EOR_W_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_W_Dx_To_Mem",_EOR_W_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EOR_W_Mem_To_Dx",_EOR_W_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EXG_Ax_Ax",_EXG_Ax_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EXG_Dx_Ax",_EXG_Dx_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EXG_Dx_Dx",_EXG_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EXT_L",_EXT_L) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_EXT_W",_EXT_W) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_JMP",_JMP) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_JSR",_JSR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LEA",_LEA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LINK",_LINK) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_B_Dx_Dx",_LSL_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_B_Nb_Dx",_LSL_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_L_Dx_Dx",_LSL_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_L_Nb_Dx",_LSL_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_W_Dx_Dx",_LSL_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_W_Nb_Dx",_LSL_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSL_W_mem",_LSL_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_B_Dx_Dx",_LSR_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_B_Nb_Dx",_LSR_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_L_Dx_Dx",_LSR_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_L_Nb_Dx",_LSR_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_W_Dx_Dx",_LSR_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_W_Nb_Dx",_LSR_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_LSR_W_mem",_LSR_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEA_L_Ax",_MOVEA_L_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEA_L_Dx",_MOVEA_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEA_L_mem",_MOVEA_L_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEA_W_Ax",_MOVEA_W_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEA_W_Dx",_MOVEA_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEA_W_mem",_MOVEA_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_L_from_mem",_MOVEM_L_from_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_L_from_mem_Aipi",_MOVEM_L_from_mem_Aipi) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_L_to_mem",_MOVEM_L_to_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_L_to_mem_Aipd",_MOVEM_L_to_mem_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_W_from_mem",_MOVEM_W_from_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_W_from_mem_Aipi",_MOVEM_W_from_mem_Aipi) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_W_to_mem",_MOVEM_W_to_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEM_W_to_mem_Aipd",_MOVEM_W_to_mem_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEP_L_From_Mem",_MOVEP_L_From_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEP_L_To_Mem",_MOVEP_L_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEP_W_From_Mem",_MOVEP_W_From_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEP_W_To_Mem",_MOVEP_W_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVEQ",_MOVEQ) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_B",_MOVE_B) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_From_SR",_MOVE_From_SR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_From_USP",_MOVE_From_USP) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_L",_MOVE_L) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_To_CCR",_MOVE_To_CCR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_To_SR",_MOVE_To_SR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_To_USP",_MOVE_To_USP) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MOVE_W",_MOVE_W) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MULS",_MULS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_MULU",_MULU) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEGX_B_Dx",_NEGX_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEGX_B_Mem",_NEGX_B_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEGX_L_Dx",_NEGX_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEGX_L_Mem",_NEGX_L_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEGX_W_Dx",_NEGX_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEGX_W_Mem",_NEGX_W_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEG_B_Dx",_NEG_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEG_B_Mem",_NEG_B_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEG_L_Dx",_NEG_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEG_L_Mem",_NEG_L_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEG_W_Dx",_NEG_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NEG_W_Mem",_NEG_W_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOP",_NOP) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOT_B_Dx",_NOT_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOT_B_Mem",_NOT_B_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOT_L_Dx",_NOT_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOT_L_Mem",_NOT_L_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOT_W_Dx",_NOT_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_NOT_W_Mem",_NOT_W_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_B_To_Dx",_ORI_B_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_B_To_Mem",_ORI_B_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_CCR",_ORI_CCR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_L_To_Dx",_ORI_L_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_L_To_Mem",_ORI_L_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_SR",_ORI_SR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_W_To_Dx",_ORI_W_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ORI_W_To_Mem",_ORI_W_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_B_Dx_To_Dx",_OR_B_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_B_Dx_To_Mem",_OR_B_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_B_Mem_To_Dx",_OR_B_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_L_Dx_To_Dx",_OR_L_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_L_Dx_To_Mem",_OR_L_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_L_Mem_To_Dx",_OR_L_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_W_Dx_To_Dx",_OR_W_Dx_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_W_Dx_To_Mem",_OR_W_Dx_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OR_W_Mem_To_Dx",_OR_W_Mem_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_PEA",_PEA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_RESET",_RESET) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_B_Dx_Dx",_ROL_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_B_Nb_Dx",_ROL_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_L_Dx_Dx",_ROL_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_L_Nb_Dx",_ROL_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_W_Dx_Dx",_ROL_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_W_Nb_Dx",_ROL_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROL_W_mem",_ROL_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_B_Dx_Dx",_ROR_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_B_Nb_Dx",_ROR_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_L_Dx_Dx",_ROR_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_L_Nb_Dx",_ROR_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_W_Dx_Dx",_ROR_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_W_Nb_Dx",_ROR_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROR_W_mem",_ROR_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_B_Dx_Dx",_ROXL_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_B_Nb_Dx",_ROXL_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_L_Dx_Dx",_ROXL_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_L_Nb_Dx",_ROXL_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_W_Dx_Dx",_ROXL_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_W_Nb_Dx",_ROXL_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXL_W_mem",_ROXL_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_B_Dx_Dx",_ROXR_B_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_B_Nb_Dx",_ROXR_B_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_L_Dx_Dx",_ROXR_L_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_L_Nb_Dx",_ROXR_L_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_W_Dx_Dx",_ROXR_W_Dx_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_W_Nb_Dx",_ROXR_W_Nb_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ROXR_W_mem",_ROXR_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_RTE",_RTE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_RTR",_RTR) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_RTS",_RTS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SCC",_SCC) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SCS",_SCS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SEQ",_SEQ) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SF",_SF) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SGE",_SGE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SGT",_SGT) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SHI",_SHI) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SLE",_SLE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SLS",_SLS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SLT",_SLT) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SMI",_SMI) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SNE",_SNE) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SPL",_SPL) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_ST",_ST) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBA_L_To_Ax",_SUBA_L_To_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBA_W_To_Ax",_SUBA_W_To_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBI_B_To_Dx",_SUBI_B_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBI_B_To_Mem",_SUBI_B_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBI_L_To_Dx",_SUBI_L_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBI_L_To_Mem",_SUBI_L_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBI_W_To_Dx",_SUBI_W_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBI_W_To_Mem",_SUBI_W_To_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_B_Dx",_SUBQ_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_B_mem",_SUBQ_B_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_L_Ax",_SUBQ_L_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_L_Dx",_SUBQ_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_L_mem",_SUBQ_L_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_W_Ax",_SUBQ_W_Ax) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_W_Dx",_SUBQ_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBQ_W_mem",_SUBQ_W_mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBX_B_Aipd",_SUBX_B_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBX_B_Dx",_SUBX_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBX_L_Aipd",_SUBX_L_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBX_L_Dx",_SUBX_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBX_W_Aipd",_SUBX_W_Aipd) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUBX_W_Dx",_SUBX_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUB_B_Dx_To_EA",_SUB_B_Dx_To_EA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUB_B_EA_To_Dx",_SUB_B_EA_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUB_L_Dx_To_EA",_SUB_L_Dx_To_EA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUB_L_EA_To_Dx",_SUB_L_EA_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUB_W_Dx_To_EA",_SUB_W_Dx_To_EA) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SUB_W_EA_To_Dx",_SUB_W_EA_To_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SVC",_SVC) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_SVS",_SVS) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_Swap",_Swap) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TRAP",_TRAP) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TRAPV",_TRAPV) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TST_B_Dx",_TST_B_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TST_B_Mem",_TST_B_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TST_L_Dx",_TST_L_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TST_L_Mem",_TST_L_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TST_W_Dx",_TST_W_Dx) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_TST_W_Mem",_TST_W_Mem) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_UNLK",_UNLK) ;
        OUTDEBUG(b) ;
        sprintf(b,"%10d -> Do_OPTIMIZED MOVE",_OPTIMIZED_MOVE) ;
        OUTDEBUG(b) ;
}
